import type { Metadata } from "next";
import { lusitana } from '@/app/ui/fonts';
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className}`}>
        <ul>
          <li><Link href="/Admin">admin</Link></li>
          <li><Link href="/Customer">customet</Link></li>
        </ul>

        {children}

        <footer>hddhdh</footer>
        <header>
          header
        </header>

      </body>

    </html>
  );
}
